/**
 * 
 */
package edu.abhi.test.stream;

import java.io.PrintStream;

/**
 * @author abhishek sarkar
 *
 */
public class CatchConsoleOutputStream {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		PrintStream sout = System.out;
		
		java.io.ByteArrayOutputStream out = new java.io.ByteArrayOutputStream();    
		System.setOut(new java.io.PrintStream(out));    

		TestConsoleOutputStream.main(args);
		
		System.setOut(sout);
		
		System.out.println("Console Output from within the jar was as below: \n\n");
		
		System.out.println(out.toString());
	}

}

//class TestConsoleOutputStream {
//	public static void main(String[] args) {
//		System.out.println("This class is to test catching of console output which is generated by an external jar");
//		System.out.println("Inside the class from where the external jar has been used");
//		System.out.println("So that, something from that console output can be processed or tested");
//		System.out.println("This is the main Agenda!!!");
//	}
//}
